#!/bin/sh
# Stand-in for mkdir that sends Ctrl-C (SIGINT to the whole process group) while 3-extract.sh
# claims the episode $INTERRUPT_ON_CLAIM, i.e. after a worker has checked for an interrupt but
# before it starts claude. Then it creates the directory as usual.
case "$*" in
  *"/claim-$INTERRUPT_ON_CLAIM")
    trap '' INT
    kill -INT 0
    sleep 0.5
    ;;
esac
exec /bin/mkdir "$@"
